import { z } from 'zod'

// We're keeping a simple non-relational schema here.
// IRL, you will have a schema for your data models.
export const taskSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: z.string(),
  label: z.string(),
  priority: z.string(),
})

export type Task = z.infer<typeof taskSchema>

// Updated to match backend inventory table schema
export const inventorySchema = z.object({
  inventory_id: z.number().int().positive().optional(), // Auto-generated by SQLite
  inventory_unique_id: z.string().min(1, 'Inventory unique ID is required'),
  product_unique_id: z.string().min(1, 'Product unique ID is required'),
  stock: z.number().int().min(0, 'Stock cannot be negative').default(0),
  retail_price: z.number().min(0, 'Retail price cannot be negative'),
  wholesale_price: z.number().min(0, 'Wholesale price cannot be negative').optional(),
  purchase_price: z.number().min(0, 'Purchase price cannot be negative').optional(),
  barcode: z.string().optional(),
  product_name: z.string().optional(),
  category_name: z.string().nullable().optional(),
  alertqty: z.number().int().min(0, 'Alert quantity cannot be negative').optional().default(0),
  product_status: z.enum(['active', 'inactive']).optional().default('active'),
  category_status: z.enum(['active', 'inactive']).optional().default('active'),
  added_by: z.string().min(1, 'Added by is required'),
  company_id: z.string().min(1, 'Company is required'),
  branch_id: z.string().min(1, 'Branch is required'),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
})

export type Inventory = z.infer<typeof inventorySchema>
