import { z } from 'zod'

// Updated to match backend categories table schema
export const categorySchema = z.object({
  category_id: z.number().int().positive().optional(), // Auto-generated by SQLite
  category_unique_id: z.string().optional(), // Made optional for form validation
  category_name: z.string().min(1, 'Category name is required'),
  description: z.string().optional(),
  status: z.enum(['active', 'inactive']).optional().default('active'),
  icon: z.string().optional(),
  added_by: z.string().optional().default('admin'),
  company_id: z.string().optional().default('1'),
  branch_id: z.string().optional().default('1'),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
  products_count: z.number().int().nonnegative().optional().default(0), // Number of products in this category
})

export type Category = z.infer<typeof categorySchema>
export type NewCategory = z.infer<typeof categorySchema> 